Repository pro00er/proMorningReader, pull requests merged in 2018-07, with the labels that each got.

#40 39_TDD실습_20180630_사당역_문자열 덧셈 계산기
  .gitignore
  tddExercise/src/stringCaculator/AddCaculation.java
  tddExercise/test/stringCaculator/AddCaculationTest.java
  tddExercise/test/stringCaculator/blueprint.md
Labels: exercise

#37 TDD실습_20180628_log작성
  tdd_training.md
Labels: log

#42 TDD 실습로그_180630_사당_문자열 덧셈 계산기
  images/180630_TDD말로해보기.png
  tdd_training.md
Labels: log

#44 43_Book_TDD_ch22_20180702_log_작성
  book_tdd_Kent_Beck.md
Labels: log

#49 48_log_180704_한달회고
  meeting_log.md
Labels: log

#51 Update Book_TDD_ch23 log
  book_tdd_Kent_Beck.md
Labels: log

#56 Fix Conflict_20180705 book tdd ch23
  book_tdd_Kent_Beck.md
Labels: bug

#59 58_Book_TDD_ch25_20180709_log_작성
  book_tdd_Kent_Beck.md
Labels: log

#57 Update Book_TDD_ch24 log
  book_tdd_Kent_Beck.md
Labels: log

#61 60_log_20180710_book_TDD_ch25_208page
  book_tdd_Kent_Beck.md
Labels: log

#46 1_날짜별 책 진도 제목에 업데이트
  book_tdd_Kent_Beck.md
Labels: doc

#54 Update meeting_log.md 20180707
  meeting_log.md
Labels: log

#71 exercise_20180715_김포공항TDD실습
  tddExercise/src/stringCaculator/AddCaculation.java
  tddExercise/test/stringCaculator/AddCaculationTest.java
  tddExercise/test/stringCaculator/blueprint.md
Labels: exercise

#65 log_20180713_book_TDD_ch25_211_212page
  book_tdd_Kent_Beck.md
Labels: log
