Repository pro00er/proMorningReader, pull requests merged in 2018-06, with the labels that each got.

#3 스터디진행 방향에 관한 meeting_log.md
  meeting_log.md
Labels: log

#11 Add gitignore file
  .gitignore
Labels: doc

#12 Autogenerated ToC of meeting_log
  meeting_log.md
Labels: doc, log

#14 Fix markdown Toc
  meeting_log.md
Labels: doc, log

#8 Book_TDD_ch.15 log 작성
  book_tdd_Kent_Beck.md
Labels: log

#16 Book_TDD_ch.16 log 작성
  book_tdd_Kent_Beck.md
Labels: log

#20 Book_TDD_ch18_20180625 log 작성
  book_tdd_Kent_Beck.md
Labels: log

#22 21_test
  README.md
Labels: help wanted

#26 Book_TDD_ch19_20180626
  book_tdd_Kent_Beck.md
Labels: log

#35 Create tdd_training.md #34
  tdd_training.md
Labels: log

#33 Add book_tdd_kent_beck_ch20_ch21
  book_tdd_Kent_Beck.md
Labels: log
